#spring.application.name=journalApp
#spring.data.mongodb.host=localhost

#spring.data.mongodb.uri=uri
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true

#spring.data.mongodb.username=admin
#spring.data.mongodb.password=admin@123
